export const SUCCESS_CODES = {
  CREATED: 201,
  SUCCESS: 200,
};

export const SUCCESS_MESSAGES = {
  HEALTH_CHECK_SUCCESS: "HEALTH CHECK SUCCESSFUL",
  DATABASE_CONNECTED: "CONNECTED TO POSTGRES",
  SERVER_RUN_SUCCESS: "SERVER STARTED ON PORT: ",
};
