import { MessageHandler } from "../../utility";

export const ERROR_CODES = {
  INTERNAL_SERVER_ERROR: 500,
  BAD_REQUEST: 400,
  NOT_FOUND: 404,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  CONFLICT: 409,
};

export const ERROR_MESSAGES = {
  INTERNAL_SERVER_ERROR: "INTERNAL SERVER ERROR",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  SERVER_RUN_FAILURE: "COULD NOT START SERVER",
  DATABASE_CONNCECTION_FAILURE: "COULD NOT CONNECT TO POSTGRES",
  NOT_FOUND: "NO DATA FOUND",
};

export const BASE_EXCEPTION_CONSTANTS = {
  INTERNAL_SERVER_ERROR: new MessageHandler(
    ERROR_CODES.INTERNAL_SERVER_ERROR,
    ERROR_MESSAGES.INTERNAL_SERVER_ERROR
  ),
  SERVER_FAILURE: new MessageHandler(
    ERROR_CODES.INTERNAL_SERVER_ERROR,
    ERROR_MESSAGES.SERVER_RUN_FAILURE
  ),
  DATABASE_FAILURE: new MessageHandler(
    ERROR_CODES.INTERNAL_SERVER_ERROR,
    ERROR_MESSAGES.DATABASE_CONNCECTION_FAILURE
  ),
  UNAUTHORIZED: new MessageHandler(
    ERROR_CODES.UNAUTHORIZED,
    ERROR_MESSAGES.UNAUTHORIZED
  ),
  FORBIDDEN: new MessageHandler(
    ERROR_CODES.FORBIDDEN,
    ERROR_MESSAGES.FORBIDDEN
  ),
};
